---

- name: "Creates/Updates {{ branch_name }} environment"
  hosts: local
  gather_facts: False
  tasks:
    - name: "Runs {{ branch_name }}-environment cloudformation stack"
      cloudformation:
        region: "{{ aws_region }}"
        stack_name: "{{ branch_name }}-environment"
        template: "./cloudformation_templates/1-environment.yml"
        state: "present"
        disable_rollback: false
        template_parameters:
          NamespaceParameter: "{{ branch_name }}"
          TemplatesBucketParameter: "{{ cf_bucket }}"
        tags:
          Stack: "{{ branch_name }}-environment"
          Environment: "{{ branch_name }}"
          Commit: "{{ commit_hash }}"

- name: "Creates/Updates Jenkins service inside the {{ branch_name }} environment"
  hosts: local
  gather_facts: False
  vars:
    service_name: "jenkins"
  tasks:
    - name: "Adds jenkins service to environment"
      cloudformation:
        region: "{{ aws_region }}"
        stack_name: "{{ branch_name }}-{{ service_name }}"
        template: "./cloudformation_templates/4-sandbox-service.yml"
        state: "present"
        disable_rollback: false
        template_parameters:
          NamespaceParameter: "{{ branch_name }}"
          ServiceNameParameter: "{{ service_name }}"
          TemplatesBucketParameter: "{{ cf_bucket }}"
          ScriptParameter: "{{lookup('file', './shells/install_{{ service_name }}.sh') }}"
        tags:
          Stack: "{{ branch_name }}-{{ service_name }}"
          Service: "{{ service_name }}"
          Environment: "{{ branch_name }}"
          Commit: "{{ commit_hash }}"