---

- name: "Create/Update {{ service }} inside an EC2 instance"
  hosts: localhost
  gather_facts: False
  vars:
    region: us-east-1
    vpc_id: vpc-07117e9acd72c9bee
    subnet_id: subnet-0f13fa5acc95f7d4b
    service_name: "{{ name }}-{{ service }}"
    stack_name: "{{ service_name }}-service"
    ami_id: ami-0de53d8956e8dcf80
    instance_type: "t2.micro"
    key_pair: "{{ service }}-pair"
  tasks:
    - name: "Executing the stack { stack_name }}"
      cloudformation:
        region: "{{ region }}"
        stack_name: "{{ stack_name }}"
        template: "./cloudformation_templates/create-service.json"
        state: "present"
        disable_rollback: false
        template_parameters:
          VpcId: "{{ vpc_id }}"
          SubnetId : "{{ subnet_id }}"
          ServiceName: "{{ service_name }}"
          AmiId: "{{ ami_id }}"
          InstanceType: "{{ instance_type }}"
          KeyPair: "{{ key_pair }}"
          Script: "https://s3.amazonaws.com/<s3_bucket>/install_{{ service }}.sh"
        tags:
          Stack: "{{ stack_name }}"
          Name: "{{ service_name }}"
          Service: "{{ service }}"