---

- name: "Creates/Updates {{ branch_name }}-{{ service_name }} service"
  hosts: local
  gather_facts: False
  vars:
    region: us-east-1
    vpc_id: vpc-07117e9acd72c9bee
    subnet_id: subnet-0f13fa5acc95f7d4b
    ami_id: ami-0de53d8956e8dcf80
    instance_type: "t2.micro"
    stack_name: "{{ service_name }}-{{ branch_name }}"
  tasks:
    - name: "Executing the cloudformation stack {{ stack_name }}"
      cloudformation:
        region: "{{ region }}"
        stack_name: "{{ stack_name }}"
        template: "./cloudformation_templates/create-{{ service_name }}-service.yml"
        state: "present"
        disable_rollback: false
        template_parameters:
          VpcParameter: "{{ vpc_id }}"
          SubnetIdParameter: "{{ subnet_id }}"
          CidrIpParameter: 0.0.0.0/0
          NamespaceParameter: "{{ branch_name }}"
          ServiceNameParameter: "{{ service_name }}"
          ImageIdParameter: "{{ ami_id }}"
          InstanceTypeParameter: "{{ instance_type }}"
          TemplatesBucketParameter: "{{ cf_bucket }}"
        tags:
          Stack: "{{ stack_name }}"
          Service: "{{ service_name }}"
          Namespace: "{{ branch_name }}"
          Commit: "{{ commit_hash }}"