---

- name: "Creates/Updates {{ branch_name }} environment"
  hosts: local
  gather_facts: False
  vars:
    region: us-east-1
    ami_id: ami-0de53d8956e8dcf80
    instance_type: "t2.micro"
    stack_name: "{{ branch_name }}-environment"
  tasks:
    - name: "Runs {{ stack_name }} cloudformation stack"
      cloudformation:
        region: "{{ region }}"
        stack_name: "{{ stack_name }}"
        template: "./cloudformation_templates/create-environment.yml"
        state: "present"
        disable_rollback: false
        template_parameters:
          NamespaceParameter: "{{ branch_name }}"
          TemplatesBucketParameter: "{{ cf_bucket }}"
        tags:
          Stack: "{{ stack_name }}"
          Environment: "{{ branch_name }}"
          Commit: "{{ commit_hash }}"