AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the security groups

Parameters:
  NamespaceParameter:
    Type: String
    Description: Prefix that will be assigned to the security group name
  CidrIpParameter:
    Type: String
    Description: IP address range (in CIDR notation)
    Default: 0.0.0.0/0

Resources:
  NoIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${NamespaceParameter}-no-ingress-sg"
      GroupDescription: Security group with no ingress rule
      VpcId:
        Fn::ImportValue: !Sub "${NamespaceParameter}-vpc"
      Tags:
      - Key: Name
        Value: !Sub "${NamespaceParameter}-no-ingress-sg"
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${NamespaceParameter}-ssh-sg"
      GroupDescription: Security group that allows incoming SSH request (por 22)
      VpcId:
        Fn::ImportValue: !Sub "${NamespaceParameter}-vpc"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref CidrIpParameter
      Tags:
      - Key: Name
        Value: !Sub "${NamespaceParameter}-ssh-sg"
  IcmpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${NamespaceParameter}-icmp-sg"
      GroupDescription: Security group that allows incoming ICMP request
      VpcId:
        Fn::ImportValue: !Sub "${NamespaceParameter}-vpc"
      SecurityGroupIngress:
      - IpProtocol: icmp
        FromPort: 8
        ToPort: -1
        CidrIp: !Ref CidrIpParameter
      Tags:
      - Key: Name
        Value: !Sub "${NamespaceParameter}-icmp-sg"

Outputs:
  NoIngressSecGrp:
    Description: Security group with no ingress rule
    Value: !Ref NoIngressSecurityGroup
    Export:
      Name: !Sub "${NamespaceParameter}-no-ingress-sg"
  SshSecGrp:
    Description: Security group that allows incoming SSH request (por 22)
    Value: !Ref SshSecurityGroup
    Export:
      Name: !Sub "${NamespaceParameter}-ssh-sg"
  IcmpSecGrp:
    Description: Security group that allows incoming ICMP request
    Value: !Ref IcmpSecurityGroup
    Export:
      Name: !Sub "${NamespaceParameter}-icmp-sg"